### ISSUE TITLE
libsm64: Tried to tick non-existant Mario with ID: 4294967295

### ISSUE THREAD

**Issue by ExtCan** [libsm64/libsm64-unity-dev#1]
I've placed Mario and the Camera as well as level geometry with the Mesh Collider and SM64 Static Terrain scripts however when I begin to play I get this error

libsm64: Tried to tick non-existant Mario with ID: 4294967295
UnityEngine.Debug:Log(Object)
LibSM64.Interop:debugPrintCallback(String) (at Assets/libsm64-unity/Runtime/Interop.cs:138)
LibSM64.Interop:sm64_mario_tick(UInt32, SM64MarioInputs&, SM64MarioState&, SM64MarioGeometryBuffers&)
LibSM64.Interop:MarioTick(UInt32, SM64MarioInputs, Vector3[], Vector3[], Vector3[], Vector2[]) (at Assets/libsm64-unity/Runtime/Interop.cs:205)
LibSM64.SM64Mario:contextFixedUpdate() (at Assets/libsm64-unity/Runtime/SM64Mario.cs:100)
LibSM64.SM64Context:FixedUpdate() (at Assets/libsm64-unity/Runtime/SM64Context.cs:35)

**Comment by SnesFX** [comment]
Hey did you ever fix this because I'm getting this error lmao.

**Comment by somario360** [comment]
Also experiencing this issue, even after doing exactly what the example scene does.

**Comment by somario360** [comment]
Figured it out, Mario needs to have valid collision to stand on in the level, otherwise he will not spawn.
